name: Generate 3D Contrib

on:
  schedule:
    - cron: "13 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          github_user_name: ${{ github.repository_owner }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: generate 3d contrib"
